name: service_provider_side
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
