// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2uAcyv_PYmK8qYLr6QXMYMVEy1_b1m8',
    appId: '1:263403486321:web:f75f68e83b9f6ea8996fd0',
    messagingSenderId: '263403486321',
    projectId: 'prive-concierge-provider',
    authDomain: 'prive-concierge-provider.firebaseapp.com',
    storageBucket: 'prive-concierge-provider.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UYYgNxhxHOIHMtfy3FS5sOO4tmIEPHk',
    appId: '1:263403486321:android:71787590e0b8a6d4996fd0',
    messagingSenderId: '263403486321',
    projectId: 'prive-concierge-provider',
    storageBucket: 'prive-concierge-provider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQeclXiGDiCM2JbrnWqcw2URoEfdUSE14',
    appId: '1:263403486321:ios:aaa6a86b9b18416e996fd0',
    messagingSenderId: '263403486321',
    projectId: 'prive-concierge-provider',
    storageBucket: 'prive-concierge-provider.firebasestorage.app',
    iosBundleId: 'com.example.serviceProviderSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQeclXiGDiCM2JbrnWqcw2URoEfdUSE14',
    appId: '1:263403486321:ios:aaa6a86b9b18416e996fd0',
    messagingSenderId: '263403486321',
    projectId: 'prive-concierge-provider',
    storageBucket: 'prive-concierge-provider.firebasestorage.app',
    iosBundleId: 'com.example.serviceProviderSide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY2uAcyv_PYmK8qYLr6QXMYMVEy1_b1m8',
    appId: '1:263403486321:web:96de5ca6bfff3c09996fd0',
    messagingSenderId: '263403486321',
    projectId: 'prive-concierge-provider',
    authDomain: 'prive-concierge-provider.firebaseapp.com',
    storageBucket: 'prive-concierge-provider.firebasestorage.app',
  );
}
